## Part 1: Preprocessing

In [1]:
!pip install tensorflow==2.14
import tensorflow
tensorflow.__version__

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 23.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 2.6 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.0
    Uninstalling wrapt-1.17.0:
      Successfully uninstalled wrapt-1.17.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes-0.4.1
  Attempting uninstall: keras
    Found existing installation: keras 3.5.0
    Uninstalling keras-3.5.0:
      Successfully uninstalled keras-3.5.0
  Attempting uninstall: google-auth-oauthlib
    Found existing inst

'2.14.0'

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# checking the number of values in each column Attrition and Department
print(attrition_df['Attrition'].value_counts())
print(attrition_df['Department'].value_counts())

Attrition
No     1233
Yes     237
Name: count, dtype: int64
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64


In [4]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [5]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [6]:
# Create a list of at least 10 column names to use as X data
list_of_columns = ['Education','Age','DistanceFromHome', 'JobSatisfaction', 'OverTime' , 'StockOptionLevel' ,
                   'WorkLifeBalance' , 'YearsAtCompany' , 'YearsSinceLastPromotion' , 'NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[list_of_columns]
X_df.head()

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [7]:
# checking the number of each unique value for OverTime column
X_df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [8]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df,y_df, test_size=0.25, random_state=42)


In [9]:
# Convert your X data to numeric data types however you see fit
label_encoder = LabelEncoder()

# Add new code cells as necessary
X_train['OverTime'] = label_encoder.fit_transform(X_train['OverTime'])
X_test['OverTime'] = label_encoder.transform(X_test['OverTime'])


In [10]:
# Printing Overtime count values and data type
overtime_count = X_train['OverTime'].value_counts()
print(overtime_count)

OverTime
0    780
1    322
Name: count, dtype: int64


In [11]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [12]:
# Create a OneHotEncoder for the Department column
encoder_Department = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
encoder_Department.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_enc_Department = encoder_Department.transform(y_train[['Department']])
y_test_enc_Department = encoder_Department.transform(y_test[['Department']])
print(y_train_enc_Department)
print(y_test_enc_Department)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [13]:
# Create a OneHotEncoder for the Attrition column
encoder_Attrition = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
encoder_Attrition.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_enc_Attrition = encoder_Attrition.transform(y_train[['Attrition']])
y_test_enc_Attrition = encoder_Attrition.transform(y_test[['Attrition']])
print(y_train_enc_Attrition)
print(y_test_enc_Attrition)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1.

In [14]:
print(X_train_scaled is None)
print(y_train_enc_Department is None)
print(y_train_enc_Attrition is None)

False
False
False


## Create, Compile, and Train the Model

In [15]:
# Find the number of columns in the X training data
columns_number = len(X_train.columns)

# Create the input layer
input_Layer = layers.Input(shape=(columns_number,), name='input_features')

# Create at least two shared layers
shared_layer_1 = layers.Dense(units=64, activation='relu', name='shared_layer_1')(input_Layer)
shared_layer_2 = layers.Dense(units=128, activation='relu', name='shared_layer_2')(shared_layer_1)


In [16]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
Department_hidden = layers.Dense(32, activation='relu', name='Department_hidden')(shared_layer_2)

# Create the output layer
Department_output = layers.Dense(3, activation='softmax', name='Department_output')(Department_hidden)



In [17]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
Attrition_hidden = layers.Dense(32, activation='relu', name='Attrition_hidden')(shared_layer_2)

# Create the output layer
Attrition_output = layers.Dense(2, activation='sigmoid', name='Attrition_output')(Attrition_hidden)



In [18]:
# Create the model
model = Model(inputs=input_Layer , outputs=[Department_output , Attrition_output])

# Compile the model
model.compile(optimizer='adam',loss={'Department_output': 'categorical_crossentropy',
              'Attrition_output': 'binary_crossentropy'},
              metrics={'Department_output': 'accuracy'
              , 'Attrition_output': 'accuracy'})


# Summarize the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_features (InputLayer  [(None, 10)]                 0         []                            
 )                                                                                                
                                                                                                  
 shared_layer_1 (Dense)      (None, 64)                   704       ['input_features[0][0]']      
                                                                                                  
 shared_layer_2 (Dense)      (None, 128)                  8320      ['shared_layer_1[0][0]']      
                                                                                                  
 Department_hidden (Dense)   (None, 32)                   4128      ['shared_layer_2[0][0]']  

In [19]:
# Train the model
model_fiting = model.fit(X_train_scaled,{'Department_output': y_train_enc_Department, 'Attrition_output': y_train_enc_Attrition},
    epochs=100,
    batch_size=32,
    validation_split=0.2)

Epoch 1/100
28/28 [==============================] - 4s 30ms/step - loss: 1.4135 - Department_output_loss: 0.8584 - Attrition_output_loss: 0.5551 - Department_output_accuracy: 0.6595 - Attrition_output_accuracy: 0.8036 - val_loss: 1.3672 - val_Department_output_loss: 0.8490 - val_Attrition_output_loss: 0.5182 - val_Department_output_accuracy: 0.6063 - val_Attrition_output_accuracy: 0.7873
Epoch 2/100
28/28 [==============================] - 0s 16ms/step - loss: 1.2046 - Department_output_loss: 0.7604 - Attrition_output_loss: 0.4442 - Department_output_accuracy: 0.6663 - Attrition_output_accuracy: 0.8388 - val_loss: 1.3413 - val_Department_output_loss: 0.8455 - val_Attrition_output_loss: 0.4957 - val_Department_output_accuracy: 0.6063 - val_Attrition_output_accuracy: 0.7873
Epoch 3/100
28/28 [==============================] - 0s 16ms/step - loss: 1.1596 - Department_output_loss: 0.7444 - Attrition_output_loss: 0.4153 - Department_output_accuracy: 0.6663 - Attrition_output_accuracy: 0.83

In [20]:
# Evaluate the model with the testing data
model_loss, Department_loss, Attrition_loss, Department_accuracy, Attrition_accuracy = model.evaluate(X_test_scaled, [y_test_enc_Department, y_test_enc_Attrition])

12/12 [==============================] - 0s 3ms/step - loss: 4.2009 - Department_output_loss: 2.9105 - Attrition_output_loss: 1.2904 - Department_output_accuracy: 0.5679 - Attrition_output_accuracy: 0.8234


In [21]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {Department_accuracy}")
print(f"Attrition Accuracy: {Attrition_accuracy}")

Department Accuracy: 0.5679348111152649
Attrition Accuracy: 0.823369562625885


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. No, **accuracy is not the best metric to use on this data** due to the **class imbalance** for both **Attrition** and **Department** since the accuracy measures how often a model's predictions are correct. It's calculated by dividing the number of correct predictions by the total number of predictions which is influenced by the majority class it works for balanced data but in this case we need to be more specific, we can use other metrics such as **Precision and Recall**, **F1-score**, **AUC-ROC**,  **Macro F1-Score** or **Top-K Accuracy**.
2.
* I used **Sigmoid activation function** for **Attrition output layers** because the sigmoid function identify the independent outputand we have Attrition unique values (Yes, No) are independent.

* I used **Softmax activation function** for **Department output layers** because the softmax function identify mutually exclusive output and we have the Department unique values ('Sales', 'Research & Development', 'Human Resources') are muatually exclusive.
3. **We can improve the model by :**
* Handeling the imbalance data by using the right metrics and resampling the training set.
* Adding more hidden layers.
* Selecting more features to the X data.
* Use more hyperparameter tunning (e.g Batch Normalization, Adam(Learning rate) , RMSProp(Learning rate).)
* Use Cross_Validation to better estimate model performance.
* raise the number of epochs.
